name: indonesia_flash_card
description: Flash card application of Indonesian language for Japanese

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.3.6+86

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## Google API package
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  google_mobile_ads: ^4.0.0
  google_fonts: ^6.1.0

  ## basic packages
  auto_size_text:
  flutter_svg: ^2.0.10+1
  flutter_gen:
  fluttertoast: ^8.0.8
  flutter_riverpod: ^2.1.2
  dio:
  logger:
  flutter_secure_storage:
  intl:
  shimmer:
  package_info: ^2.0.2
  shared_preferences: ^2.2.3

  ## Firebase packages
  firebase_core: ^2.31.1
  firebase_crashlytics: ^3.5.6
  firebase_messaging: ^14.9.3
  firebase_analytics: ^10.10.6
  cloud_firestore: ^4.17.4
  firebase_remote_config: ^4.4.6

  lottie: ^3.1.2
  carousel_slider: ^4.2.1
  curved_navigation_bar: ^1.0.3
  flutter_inappwebview:
  floor: ^1.4.2
  collection:
  flutter_tts: ^4.0.2
  flutter_switch: ^0.3.2
  material_floating_search_bar_2: ^0.5.0
  app_tracking_transparency: ^2.0.5
  pull_to_refresh: ^2.0.0
  pin_code_fields: ^8.0.1
  flutter_countdown_timer: ^4.1.0
  in_app_review: ^2.0.9
  flutter_dialogs: ^3.0.0
  social_share: ^2.3.1
  screenshot: ^3.0.0
  percent_indicator: ^4.2.3
  font_awesome_flutter:
  json_path:
  timeago:
  rflutter_alert: ^2.0.7
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  floor_generator: ^1.2.0
  pedantic_mono:
  flutter_gen_runner:
  dependency_validator:

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/lottie/
    - assets/prefecture_indonesia/
    - assets/svg/
    - assets/png/
    - assets/gif/
    - assets/dot/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: '#FFEBEE'
  image: 'assets/icon/app_icon_512.png'
  color_dark: '#FFEBEE'
  image_dark: 'assets/icon/app_icon_512.png'
  fullscreen: true
  android_12:
    icon_background_color: '#FFEBEE'
    image: 'assets/icon/app_icon_512.png'
    icon_background_color_dark: '#FFEBEE'
    image_dark: 'assets/icon/app_icon_512.png'
