name: indonesia_flash_card
description: Flash card application of Indonesian language for Japanese

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

  ## Google API package
  googleapis: ^5.0.1
  googleapis_auth: ^1.1.0

  ## basic packages
  auto_size_text:
  flutter_svg: ^1.0.3
  flutter_gen:
  fluttertoast: ^8.0.8
  flutter_riverpod: ^1.0.3
  dio:
  logger:
  flutter_secure_storage:
  intl:
  shimmer:
  package_info: ^2.0.2

  ## Firebase packages
  firebase_core:
  firebase_crashlytics:
  firebase_messaging:

  lottie: ^1.2.2
  carousel_slider: ^4.0.0
  curved_navigation_bar: ^1.0.3
  flutter_inappwebview:
  floor: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  floor_generator: ^1.2.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/lottie/
    - assets/prefecture_indonesia/
    - assets/svg/
    - assets/png/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true
