name: indonesia_flash_card
description: Flash card application of Indonesian language for Japanese

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.5.2+100

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ## Google API package
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  google_mobile_ads: ^6.0.0
  google_fonts: ^6.2.1

  ## basic packages
  auto_size_text:
  flutter_svg: ^2.1.0
  flutter_gen:
  fluttertoast: ^8.2.12
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  logger:
  flutter_secure_storage: ^9.2.4
  intl:
  shimmer:
  package_info_plus: ^8.3.0
  shared_preferences: ^2.5.3

  ## Firebase packages
  firebase_core: ^3.13.1
  firebase_crashlytics: ^4.3.6
  firebase_messaging: ^15.2.6
  firebase_analytics: ^11.4.6
  cloud_firestore: ^5.6.8
  firebase_remote_config: ^5.4.4

  lottie: ^3.3.1
  curved_navigation_bar: ^1.0.6
  flutter_inappwebview: ^6.1.5
  floor: ^1.5.0
  collection:
  flutter_tts: ^4.2.3
  flutter_switch: ^0.3.2
  material_floating_search_bar_2: ^0.5.0
  app_tracking_transparency: ^2.0.6+1
  pull_to_refresh: ^2.0.0
  pin_code_fields: ^8.0.1
  flutter_countdown_timer: ^4.1.0
  in_app_review: ^2.0.10
  flutter_dialogs: ^3.0.0
  social_share:
    git:
      url: https://github.com/midoandev/social_share.git
      ref: 789c3c9a85feb3bd299c5227f66c80eec7734d39
  screenshot: ^3.0.0
  percent_indicator: ^4.2.5
  font_awesome_flutter:
  json_path:
  timeago:
  rflutter_alert: ^2.0.7
  flutter_native_splash: ^2.4.6
  flutter_staggered_grid_view: ^0.7.0
  infinite_carousel: ^1.1.1
  flutter_markdown: ^0.7.7+1
  audioplayers: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  floor_generator: ^1.5.0
  pedantic_mono:
  flutter_gen_runner:
  dependency_validator:
  import_sorter:

dependency_overrides:
  path: 1.9.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/lottie/
    - assets/prefecture_indonesia/
    - assets/svg/
    - assets/png/
    - assets/dot/
    - assets/sounds/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: '#FFEBEE'
  image: 'assets/icon/app_icon_512.png'
  color_dark: '#FFEBEE'
  image_dark: 'assets/icon/app_icon_512.png'
  fullscreen: true
  android_12:
    icon_background_color: '#FFEBEE'
    image: 'assets/icon/app_icon_512.png'
    icon_background_color_dark: '#FFEBEE'
    image_dark: 'assets/icon/app_icon_512.png'
