name: indonesia_flash_card
description: Flash card application of Indonesian language for Japanese

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

  ## Google API package
  googleapis: ^5.0.1
  googleapis_auth: ^1.1.0

  ## basic packages
  auto_size_text:
  flutter_svg: ^1.0.3
  flutter_gen:
  fluttertoast: ^8.0.8
  flutter_riverpod:
  dio:
  logger:
  flutter_secure_storage:

  ## Firebase packages
  firebase_core:
  firebase_crashlytics:
  firebase_messaging:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/
